### ISSUE TITLE
Confusing comment

### ISSUE THREAD

**Issue by JoshCheek** [HaxeFlixel/flixel-templates#15]
Hi, going through the tuts. This is my first Haxe and Flash project, and I've never made a game before, so I don't know much about the infrastructure of things like this. Perhaps people with more experience will understand [this comment](https://github.com/HaxeFlixel/flixel-templates/blob/5ef12665970feba854f32e1bb2ee515e439825df/default/source/MenuState.hx#L16), but it's very confusing to me (meaning that I have difficulty even parsing it):

```haxe
// file: default/source/MenuState.hx

// ...
class MenuState extends FlxState
{
	/**
	 * Function that is called up when to state is created to set it up. 
	 */
	override public function create():Void
	{
// ...
```

**Comment by ashes999** [comment]
@JoshCheek treat it like a constructor. That's essentially (almost) what it is. It's a bit later in the object life-cycle.

**Comment by Gama11** [comment]
Not sure how this comment could be improved, feel free to suggest something else though.
