### ISSUE TITLE
Consider changing the default skipSplash to true...

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel-templates#16]
I think it should be the dev's job to change it back ***in the end***, when he finally decides to release his game. Defaulting to it during development doesn't serve its purpose, as you can't promote Flixel to yourself while iterating...

**Comment by Gama11** [comment]
Default settings are powerful (opt-in vs opt-out), I doubt many people would be end up using the splash screen if it wasn't the default.

Besides, the splash is disabled by default for debug builds, which is what you should be using during development.

**Comment by sruloart** [comment]
What I should have been using, if it was necessary in early builds and/or reflected performance reliably, but alright :)

**Comment by Gama11** [comment]
Sure, there are situations where release builds are necessary for testing, what I meant to say is "what you typically use". Still, it seems simple enough to change the value of a boolean for that?

**Comment by sruloart** [comment]
I like making lots and lots of small projects to test ideas individually, so it adds up I'm afraid. It's not a big deal of course, but maybe it would be possible to add a more complex command that allows you to build the template with your own defaults, I dunno...

**Comment by Gama11** [comment]
Adding your own templates is already possible actually, it's just not really documented. Just duplicate the "default" or "barebones" folder and make your changes. You can chose which template to use in the `tpl` command:

`flixel tpl <template-foldername> -n "Name"`

Of course, `<template-foldername>` is optional and defaults to [default](https://github.com/HaxeFlixel/flixel-templates/tree/dev/default).

**Comment by sruloart** [comment]
Oh, that's a great idea! to the documentations pronto! :D
