### ISSUE TITLE
Change default build target in VS Code settings

### ISSUE THREAD

**Issue by TheSpydog** [HaxeFlixel/flixel-templates#36]
I noticed the default build target in `.vscode/settings.json` is set to Neko, but `flixel create` builds a Flash project for code completion. This means that every time I open a new project in VS Code, I don't get fast code completion until I either run a Neko build or switch to the Flash target.

Could we change either the default target to Flash in `settings.json` or change the initial build target for `flixel create` to Neko or HTML5?

**Comment by Gama11** [comment]
Hm, good point.. Although if we solve https://github.com/openfl/lime-vscode-extension/issues/44, then that initial build won't be needed anymore.

**Comment by TheSpydog** [comment]
I agree that's a much better solution. If that issue might take a while to solve, though, I think changing the initial build target would be a nice temporary fix.
