### ISSUE TITLE
Broken .xsd links

### ISSUE THREAD

**Issue by TheHENOOB** [HaxeFlixel/flixel-templates#37]
Due to lime.software domain recently being unavailable, the XML Schema link that provides code completion and linting on the Project.xml file is broken.
`<project xmlns="http://lime.software/project/1.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lime.software/project/1.0.2 http://lime.software/xsd/project-1.0.2.xsd">`

**Comment by Geokureli** [comment]
Please create an issue in the [openfl issues page](https://github.com/openfl/openfl/issues)
